export const testEmail = 'test@test.com';
export const password = "asdfasd'1";
export const topicTitle = 'React';
export const articleTitle = 'React article';
export const fileName = 'uploaded pdf';
export const numPages = 333;
export const lastPageRead = 200;
export const url = 'https://localhost';
export const youtubeTitle = 'youtubne';
